package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"

	"github.com/example/dpc-dataloader-demo/graph/model"
	"github.com/example/dpc-dataloader-demo/internal/dataloader"
)

// ─── Query Resolvers ───────────────────────────────────────────────
// These are the top-level entry points. They delegate to the service layer,
// which returns flat data WITHOUT nested drugs/documents.

// GetPaginatedRedemptionList is the resolver for the getPaginatedRedemptionList field.
func (r *queryResolver) GetPaginatedRedemptionList(ctx context.Context, input model.PaginatedRedemptionListInput) (*model.PaginatedRedemptionListResponse, error) {
	return r.RedemptionSvc.GetPaginatedRedemptionList(ctx, input)
}

// GetRedemptionDetails is the resolver for the getRedemptionDetails field.
func (r *queryResolver) GetRedemptionDetails(ctx context.Context, redemptionID string) (*model.RedemptionDetailsResponse, error) {
	return r.RedemptionSvc.GetRedemptionDetails(ctx, redemptionID)
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	return "OK", nil
}

// ─── RedemptionDetailsResponse Field Resolvers ─────────────────────
// These are called by gqlgen ONLY when the client requests these fields.
// They use the DataLoader to batch and cache the database calls.

// RedemptionDrugs is the resolver for the redemption_drugs field.
func (r *redemptionDetailsResponseResolver) RedemptionDrugs(ctx context.Context, obj *model.RedemptionDetailsResponse) ([]*model.RedemptionDrugDetail, error) {
	if obj.RedemptionID == nil {
		return nil, nil
	}
	loaders := dataloader.For(ctx)
	if loaders == nil {
		return nil, fmt.Errorf("dataloader not found in context — is the middleware applied?")
	}
	// Load() will either:
	// 1. Return a cached result if this redemption_id was already loaded in this request
	// 2. Batch this key with other concurrent Load() calls and execute ONE SQL query
	return loaders.RedemptionDrugsByRedemptionID.Load(ctx, *obj.RedemptionID)
}

// AcknowledgeDocuments is the resolver for the acknowledge_documents field.
func (r *redemptionDetailsResponseResolver) AcknowledgeDocuments(ctx context.Context, obj *model.RedemptionDetailsResponse) ([]*model.AcknowledgeDocumentDetail, error) {
	if obj.RedemptionID == nil {
		return nil, nil
	}
	loaders := dataloader.For(ctx)
	if loaders == nil {
		return nil, fmt.Errorf("dataloader not found in context — is the middleware applied?")
	}
	return loaders.AcknowledgeDocsByRedemptionID.Load(ctx, *obj.RedemptionID)
}

// ─── RedemptionInfo Field Resolvers ────────────────────────────────
// Same pattern as above, but for the list item type.
// When getPaginatedRedemptionList returns 10 items and the client requests
// `redemption_drugs`, gqlgen calls this resolver 10 times concurrently.
// The DataLoader collects all 10 redemption_ids and makes ONE SQL query.

// RedemptionDrugs is the resolver for the redemption_drugs field.
func (r *redemptionInfoResolver) RedemptionDrugs(ctx context.Context, obj *model.RedemptionInfo) ([]*model.RedemptionDrugDetail, error) {
	if obj.RedemptionID == nil {
		return nil, nil
	}
	loaders := dataloader.For(ctx)
	if loaders == nil {
		return nil, fmt.Errorf("dataloader not found in context — is the middleware applied?")
	}
	return loaders.RedemptionDrugsByRedemptionID.Load(ctx, *obj.RedemptionID)
}

// AcknowledgeDocuments is the resolver for the acknowledge_documents field.
func (r *redemptionInfoResolver) AcknowledgeDocuments(ctx context.Context, obj *model.RedemptionInfo) ([]*model.AcknowledgeDocumentDetail, error) {
	if obj.RedemptionID == nil {
		return nil, nil
	}
	loaders := dataloader.For(ctx)
	if loaders == nil {
		return nil, fmt.Errorf("dataloader not found in context — is the middleware applied?")
	}
	return loaders.AcknowledgeDocsByRedemptionID.Load(ctx, *obj.RedemptionID)
}

// ─── Resolver Type Registrations ───────────────────────────────────

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// RedemptionDetailsResponse returns RedemptionDetailsResponseResolver implementation.
func (r *Resolver) RedemptionDetailsResponse() RedemptionDetailsResponseResolver {
	return &redemptionDetailsResponseResolver{r}
}

// RedemptionInfo returns RedemptionInfoResolver implementation.
func (r *Resolver) RedemptionInfo() RedemptionInfoResolver { return &redemptionInfoResolver{r} }

type queryResolver struct{ *Resolver }
type redemptionDetailsResponseResolver struct{ *Resolver }
type redemptionInfoResolver struct{ *Resolver }
