// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AcknowledgeDocumentDetail struct {
	ID           *int    `json:"id,omitempty"`
	FileName     string  `json:"file_name"`
	FileURL      string  `json:"file_url"`
	Remarks      *string `json:"remarks,omitempty"`
	CreatedBy    *string `json:"created_by,omitempty"`
	CreatedAt    *string `json:"created_at,omitempty"`
	RedemptionID string  `json:"redemption_id"`
}

type PaginatedRedemptionListInput struct {
	Order     *string `json:"order,omitempty"`
	Limit     *int    `json:"limit,omitempty"`
	Offset    *int    `json:"offset,omitempty"`
	ProgramID *string `json:"program_id,omitempty"`
}

type PaginatedRedemptionListResponse struct {
	Count int               `json:"count"`
	Items []*RedemptionInfo `json:"items,omitempty"`
}

type Query struct {
}

type RedemptionDetailsResponse struct {
	RedemptionID         *string                      `json:"redemption_id,omitempty"`
	RedemptionOrderID    *string                      `json:"redemption_order_id,omitempty"`
	PatientName          *string                      `json:"patient_name,omitempty"`
	ProgramName          *string                      `json:"program_name,omitempty"`
	RedemptionStatus     *string                      `json:"redemption_status,omitempty"`
	RedemptionDrugs      []*RedemptionDrugDetail      `json:"redemption_drugs,omitempty"`
	AcknowledgeDocuments []*AcknowledgeDocumentDetail `json:"acknowledge_documents,omitempty"`
}

type RedemptionDrugDetail struct {
	RedemptionID       string  `json:"redemption_id"`
	DrugID             *int    `json:"drug_id,omitempty"`
	DrugName           *string `json:"drug_name,omitempty"`
	DrugDosage         *string `json:"drug_dosage,omitempty"`
	DrugUnit           *string `json:"drug_unit,omitempty"`
	DrugSkuCodeID      *int    `json:"drug_sku_code_id,omitempty"`
	SkuName            *string `json:"sku_name,omitempty"`
	SkuDescription     *string `json:"sku_description,omitempty"`
	RedemptionQuantity *int    `json:"redemption_quantity,omitempty"`
}

type RedemptionInfo struct {
	ID                      *int                         `json:"id,omitempty"`
	RedemptionID            *string                      `json:"redemption_id,omitempty"`
	RedemptionOrderID       *string                      `json:"redemption_order_id,omitempty"`
	PurchaseCycle           *int                         `json:"purchase_cycle,omitempty"`
	PatientName             *string                      `json:"patient_name,omitempty"`
	PatientID               *string                      `json:"patient_id,omitempty"`
	EnrolmentID             *string                      `json:"enrolment_id,omitempty"`
	RedemptionStatus        *string                      `json:"redemption_status,omitempty"`
	RedemptionOrderStatus   *string                      `json:"redemption_order_status,omitempty"`
	RedemptionRequestStatus *string                      `json:"redemption_request_status,omitempty"`
	CreatedAt               *string                      `json:"created_at,omitempty"`
	ProgramID               *string                      `json:"program_id,omitempty"`
	ProgramName             *string                      `json:"program_name,omitempty"`
	DisplayID               *string                      `json:"display_id,omitempty"`
	RedemptionReceivedDate  *string                      `json:"redemption_received_date,omitempty"`
	RedemptionOrderHciName  *string                      `json:"redemption_order_hci_name,omitempty"`
	RedemptionOrderHciID    *int                         `json:"redemption_order_hci_id,omitempty"`
	RedemptionDrugs         []*RedemptionDrugDetail      `json:"redemption_drugs,omitempty"`
	AcknowledgeDocuments    []*AcknowledgeDocumentDetail `json:"acknowledge_documents,omitempty"`
	RedemptionBatchNo       *string                      `json:"redemption_batch_no,omitempty"`
}
